version: "3"
services:
  web:
    image: organization-name/project-name # IMAGE_NAME value from circleci
    environment:
      ENV: development
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: "psql://postgres:postgres@localhost:5432/app"
    command: manage test
    depends_on: 
      - db

  db:
    image: circleci/postgres:9.6.6-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app