version: "3"
services:
  web:
    image: organization-name/project-name # IMAGE_NAME value from circleci
    environment:
      ENV: development
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: "psql://postgres:postgres@127.0.0.1:5432/app"
    command: manage test

  db:
    image: circleci/postgres:9.6.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app