version: '2'
services:
  web:
    build: .
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8000:8000"
    environment:
      ENV: "development"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "postgres"
