version: '2'
services:
  web:
    build: .
    command: bash -c "python docker/web/check_db.py --service-name Postgres --ip db --port 5432 &&
                      python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 'postgres'
