variable "environment" {}
variable "project_name" {}
variable "region" {}
variable "availability_zone_1" {}
variable "availability_zone_2" {}
variable "private_security_group_id" {}
variable "public_security_group_id" {}
variable "private_subnet_1_id" {}
variable "private_subnet_2_id" {}
variable "public_subnet_1_id" {}
variable "public_subnet_2_id" {}
variable "vpc_id" {}
variable "ecs_instance_role" {}
variable "ecs_service_role" {}
variable "ecs_instance_profile_id" {}
variable "instance_type" {}
variable "max_instances" {}
variable "min_instances" {}
variable "desired_instances" {}
variable "domains" {}
variable "app_bucket" {}
variable "database" {}
variable "backend_secret_key" {}
variable "backend_email_from" {}
variable "public_key" {}
