variable "environment" {}
variable "project_name" {}
variable "region" {}
variable "private_secutity_group_id" {}
variable "public_secutity_group_id" {}
variable "private_subnet_id" {}
variable "private_subnet_2_id" {}
variable "public_subnet_id" {}
variable "public_subnet_2_id" {}
variable "vpc_id" {}
variable "ecs_instance_role" {}
variable "ecs_service_role" {}
variable "ecs_instance_profile_id" {}
variable "instance_type" {}
variable "max_instances" {}
variable "min_instances" {}
variable "desired_instances" {}
variable "domains" {}
variable "app_bucket" {}
variable "database" {}
variable "backend_secret_key" {}
variable "backend_email_from" {}
