version: "3"
services:
  web:
    image: {{ cookiecutter.organization_name }}/{{ cookiecutter.project_name }}
    volumes:
      - .:/usr/src/app
    environment:
      ENV: testing
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: "psql://postgres:postgres@db:5432/app"
    entrypoint: scripts/testing.sh
    depends_on:
      - db

  db:
    image: circleci/postgres:9.6.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
