variable "region" {}
variable "project_name" {}
variable "environment" {}
variable "vpc_id" {}
variable "db_storage_size" {}
variable "db_instance_type" {}
variable "private_security_group" {}
variable "private_subnet_id" {}
variable "private_subnet_2_id" {}
variable "db_username" {}
variable "db_password" {}
